### PR TITLE
Tickets/preops 3453

### PR DESCRIPTION
**Pull request by galaxyumi**
Completed updating the Portal tutorial 1 to match the latest updates.

### CODE REVIEW

**Review by MelissaGraham — DISMISSED** [review]
I see this PR#88 and review request for the updates to Portal Tutorial 01, but you can go ahead and do Portal Tutorials 02, 03, and also the instructions page, and then ask for a review once it's all ready. Then you only need someone to review once, instead of four times (if your plan was separate PRs for each tutorial and for the instructions page).

When it is ready, we can have @Madejski review it all.

**Comment by galaxyumi** [comment]
@Madejski This PR is now ready for review.

**Review by Madejski — APPROVED** [review]
Looks fine, no issues for the Portal 2.  But for the Portal Intro, I see one of the screenshots is wrong.  Specifically in the Section "Image Search (ObsTAP) the second screenshot is not a "results" view.  

Otherwise, I think it is fine.

**Review by Madejski — APPROVED** [review]

**Comment by galaxyumi** [comment]
> I see this PR#88 and review request for the updates to Portal Tutorial 01, but you can go ahead and do Portal Tutorials 02, 03, and also the instructions page, and then ask for a review once it's all ready. Then you only need someone to review once, instead of four times (if your plan was separate PRs for each tutorial and for the instructions page).
> 
> When it is ready, we can have @Madejski review it all.

Yes, it's been done this suggested way.

**Review by GloriaFA — APPROVED** [review]
Portal 3 looks good.

**Pull request merged**
