### PR TITLE
tickets/PREOPS-1233

### PR DESCRIPTION
**Pull request by MelissaGraham**
Done updating the Notebook Aspect documentation.

### CODE REVIEW

**Comment by MelissaGraham** [comment]
Added @DukeofSuffolk as reviewer to get help removing the early commits from Greg, which shouldn't be in this branch.

**Review by ChristinaAdair — APPROVED** [review]
Looks good.  The links all seemed logical and I was able to execute the commands in the write up.  I got an error when I tried using the butler -help command but butler -h worked.

**Comment by DukeofSuffolk** [comment]
Removed bad commits - approved for this purpose.

**Review by DukeofSuffolk — APPROVED** [review]
Removed bad commits - approved for this purpose.

**Pull request merged**
