### PR TITLE
Tickets/preops 3435

### PR DESCRIPTION
**Pull request by ameisner**
significant revision/upgrade of DP0.2 command line tutorial 02 to additionally include the relevant portion of DP0.2 tutorial notebook 9b: detection, deblending, and measurement run on the custom coadd

### CODE REVIEW

**Review by MelissaGraham — APPROVED** [review]
Going to leave the comments here instead of embedding, and I'm going to approve the PR b/c once they're addressed it's OK to merge (they're not to do with functionality).

Some of these are not specifically about the new Step 5, sorry! I let my review go outside the bounds of the update but I'd still like to have the points implemented.

Working through the command-line tutorial I think we might need to break up the big paragraphs more. For example, Step 2.3 is quite long. With the Portal tutorials we have one step per user action, or one step per "piece of information learned". Sometimes longer blocks are inevitable of course. But a step can be even just "Notice that ..." or "Be advised that...". Dividing paragraphs up even without labeling a new step would be OK too I think.

I think also we should separate code blocks that are code, that can/should be copy-pasted, and code blocks that display the output. And remove the $ and > to make the code more copy-pastable. And also have each code block fully copy-pasteable and executable, e.g., the last code block before Step 3 is only partial. 

Could we make it clearer that the code to create the quantum graph is optional? Like in NBs, we write **Optional**: before the instruction.

Re. dividing up blocks of text, could use bullet points when describing, e.g., what each argument means (Step 5.2)

Under exercises for the learner, I think the first bullet needs to be updated, because 09b has been updated. Maybe two options. Could specify Steps 1, 2, 3, 4 are covered by 09a, and so the result of Step 4 can be used as input to 09b. Could also specify in second bullet that Step 5 is covered by Section X of 09b, and say how users can start in Section Y and retrieve and analyze the results of Step 5.

**Comment by ameisner** [comment]
> Could we make it clearer that the code to create the quantum graph is optional? Like in NBs, we write Optional: before the instruction.

I think I was originally imagining the quantum graph stuff being non-optional when I wrote the text. But I'm happy to make it optional. When you say "create the quantum graph", does that refer to the `pipetask qgraph` command in Section 3.1, or the `pipetask build` commands to make the graph visualizations in Sections 3.2 and 5.1? Or all of the above? Thanks...

@MelissaGraham

**Comment by MelissaGraham** [comment]
> > Could we make it clearer that the code to create the quantum graph is optional? Like in NBs, we write Optional: before the instruction.
> 
> I think I was originally imagining the quantum graph stuff being non-optional when I wrote the text. But I'm happy to make it optional. When you say "create the quantum graph", does that refer to the `pipetask qgraph` command in Section 3.1, or the `pipetask build` commands to make the graph visualizations in Sections 3.2 and 5.1? Or all of the above? Thanks...
> 
> @MelissaGraham

Yes the two commands that make the graphs. I skipped them both to save time and that's an OK thing for users to do right?

**Comment by ameisner** [comment]
> Yes the two commands that make the graphs. I skipped them both to save time and that's an OK thing for users to do right?

Yeah, they can be skipped in the interest of time. Thanks!

**Comment by ameisner** [comment]
> Could we make it clearer that the code to create the quantum graph is optional? Like in NBs, we write Optional: before the instruction.

Done in [9d084f1](https://github.com/lsst/dp0-2_lsst_io/pull/125/commits/9d084f189cdf1c5a44ed0dd2f419962a3dd647ba) and [833af57](https://github.com/lsst/dp0-2_lsst_io/pull/125/commits/833af57d81a0ad70ab3ad600934cc563c3ded24e).

**Comment by ameisner** [comment]
> code blocks that display the output. And remove the $ and > to make the code more copy-pastable.

Done in [2dba65d](https://github.com/lsst/dp0-2_lsst_io/pull/125/commits/2dba65daf0e0747bd16d5a55ebe808697d096958) and [43b3a2f](https://github.com/lsst/dp0-2_lsst_io/pull/125/commits/43b3a2f8d3e9a874d4ce7db689bf34c7830712ec)

**Comment by ameisner** [comment]
> And also have each code block fully copy-pasteable and executable, e.g., the last code block before Step 3 is only partial.

Done in [e9a6892](https://github.com/lsst/dp0-2_lsst_io/pull/125/commits/e9a68920b40e5e5ac2e820ed61d76e3f966698c9)

**Comment by ameisner** [comment]
> Re. dividing up blocks of text, could use bullet points when describing, e.g., what each argument means (Step 5.2)

Good idea, thanks. Done in [d967d72](https://github.com/lsst/dp0-2_lsst_io/pull/125/commits/d967d726624f0f55eb4a90167fa64911a81f9039)

**Comment by ameisner** [comment]
> Under exercises for the learner, I think the first bullet needs to be updated, because 09b has been updated. Maybe two options. Could specify Steps 1, 2, 3, 4 are covered by 09a, and so the result of Step 4 can be used as input to 09b. Could also specify in second bullet that Step 5 is covered by Section X of 09b, and say how users can start in Section Y and retrieve and analyze the results of Step 5.

Good catch, thanks! Implemented in [c27a799](https://github.com/lsst/dp0-2_lsst_io/pull/125/commits/c27a799ef2cf9c77c1a6af917c19d6de5643c07b)

**Comment by ameisner** [comment]
> Working through the command-line tutorial I think we might need to break up the big paragraphs more. For example, Step 2.3 is quite long. With the Portal tutorials we have one step per user action, or one step per "piece of information learned". Sometimes longer blocks are inevitable of course. But a step can be even just "Notice that ..." or "Be advised that...". Dividing paragraphs up even without labeling a new step would be OK too I think.

Good ideas. I've split a couple more steps into substeps and also broke out another long paragraph into bullet points in [3fd8309](https://github.com/lsst/dp0-2_lsst_io/pull/125/commits/3fd8309b8c9de00a87925b27d2d5072c87f2d771).

**Comment by ameisner** [comment]
Your comments about style and uniformity in the command line context here are really great 👍 . I wonder if we should try to translate the items **specific to command line tutorials** into some sort of set of guidelines for anyone developing CST command line tutorials. Perhaps this can wait until we've published first versions of N > 1 command line tutorials using ``pipetask``/``butler``.

**Pull request merged**
